lib: [
  "_build/install/default/lib/olmi/META" {"META"}
  "_build/install/default/lib/olmi/opam" {"opam"}
  "_build/install/default/lib/olmi/olmi.cmi"
  "_build/install/default/lib/olmi/olmi.cmx"
  "_build/install/default/lib/olmi/olmi.cmt"
  "_build/install/default/lib/olmi/olmi.ml"
  "_build/install/default/lib/olmi/olmi__OlmiInterfaces.cmi"
  "_build/install/default/lib/olmi/olmi__OlmiInterfaces.cmx"
  "_build/install/default/lib/olmi/olmi__OlmiInterfaces.cmt"
  "_build/install/default/lib/olmi/olmiInterfaces.ml"
  "_build/install/default/lib/olmi/olmi__OlmiMake.cmi"
  "_build/install/default/lib/olmi/olmi__OlmiMake.cmx"
  "_build/install/default/lib/olmi/olmi__OlmiMake.cmt"
  "_build/install/default/lib/olmi/olmiMake.ml"
  "_build/install/default/lib/olmi/olmi__.cmi"
  "_build/install/default/lib/olmi/olmi__.cmx"
  "_build/install/default/lib/olmi/olmi__.cmt"
  "_build/install/default/lib/olmi/olmi__.ml-gen"
  "_build/install/default/lib/olmi/olmi.cma"
  "_build/install/default/lib/olmi/olmi.cmxa"
  "_build/install/default/lib/olmi/olmi.a"
  "_build/install/default/lib/olmi/olmi.cmxs"
]
doc: [
  "_build/install/default/doc/olmi/README.md"
  "_build/install/default/doc/olmi/LICENSE"
]
